spring:
  flyway:
    locations: classpath:db.migration
    url: jdbc:postgresql://localhost:5432/beerdb
    user: postgres
    password: password
    baseline-on-migrate: true
#    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/beerdb
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: update
#      ddl-auto: create-drop
      ddl-auto: validate
#    show-sql: true

jwt:
  secret:
    key: "439adb87583df62d6ef6ba54faf42945c9ca704f7069f975898d1f7210ad05f6"
  expiration: 24h

